// ---------------------------------------------------------------------------------------------
// --------------- WARNING: this code is generated by an automatic code generator --------------
// ---------------------------------------------------------------------------------------------
// -------------- WARNING: any modifications made to this code will be overwritten -------------
// ---------------------------------------------------------------------------------------------

#ifndef __classcap___H
#define __classcap___H

#include "us_hydrodyn.h"

using namespace std;

class US_EXTERN __class__ : public QDialog
{
   Q_OBJECT

   public:
      __class__(
                       void                     *              us_hydrodyn,
                       map < QString, QString > *              parameters,
                       QWidget *                               p = 0,
                       const char *                            name = ""
                       );

      ~__class__();

   private:

      US_Config *                             USglobal;
      void                                    setupGUI();
      map < QString, QString > *              parameters;
      void *                                  us_hydrodyn;
      vector < QPushButton * >                bottom_row_buttons;
      map < QWidget *, vector < QWidget * > > repeats;
      void                                    showhide( vector < QWidget * > &, bool isChecked );

      QPushButton *                           pb_help;
      QPushButton *                           pb_cancel;

