use strict;
use warnings;

use File::Spec;
use FindBin;
use JSON qw(decode_json);
use Test::More;

use lib File::Spec->catdir( $FindBin::Bin, '..', 'lib' );
use GenAppTest qw(generate_fixture_app read_file repo_root);

my $repo_root = repo_root( File::Spec->catdir( $FindBin::Bin, '..' ) );
my $generated = generate_fixture_app(
    repo_root    => $repo_root,
    fixture_name => 'ui2_views',
    test_dir     => File::Spec->catdir( $FindBin::Bin, '..' ),
);

is( $generated->{status}, 0, 'ui2_views fixture generates ui2 output' )
    or diag("command failed ($generated->{status}): $generated->{quoted}\n$generated->{output}");

my $app_dir = $generated->{app_dir};
my $ui2     = File::Spec->catdir( $app_dir, qw(output ui2) );

ok( -f File::Spec->catfile( $ui2, 'index.html' ), 'ui2 index was generated' );
ok( -f File::Spec->catfile( $ui2, qw(js app-map.js) ), 'ui2 app map was generated' );
ok( -f File::Spec->catfile( $ui2, qw(css ui2.css) ), 'ui2 stylesheet was copied' );
ok( -f File::Spec->catfile( $ui2, qw(js ui2.js) ), 'ui2 script was copied' );
ok( -f File::Spec->catfile( $ui2, qw(react ui2-react.css) ), 'ui2 React stylesheet was copied' );
ok( -f File::Spec->catfile( $ui2, qw(react ui2-react.js) ), 'ui2 React bundle was copied' );
ok( -f File::Spec->catfile( $ui2, qw(modules shared.json) ), 'ui2 shared module summary was generated' );
ok( -f File::Spec->catfile( $ui2, qw(modules plain.json) ), 'ui2 plain module summary was generated' );
ok( -f File::Spec->catfile( $ui2, qw(modules typed.json) ), 'ui2 typed module summary was generated without ui2 type templates' );
ok( -f File::Spec->catfile( $ui2, qw(modules sys_user_config.json) ), 'ui2 config system module summary was generated' );
ok( -f File::Spec->catfile( $ui2, qw(modules sys_file_manager.json) ), 'ui2 configbase system module summary was generated' );
ok( -f File::Spec->catfile( $ui2, qw(modules sys_feedback.json) ), 'ui2 feedback system module summary was generated' );

my $index      = read_file( File::Spec->catfile( $ui2, 'index.html' ) );
my $app_map_js = read_file( File::Spec->catfile( $ui2, qw(js app-map.js) ) );
like( $index, qr/js\/app-map\.js/, 'ui2 index loads the generated app map' );
like( $index, qr/\.\.\/js\/autobahn\.min\.js/, 'ui2 index preloads the existing legacy Autobahn websocket client' );
like( $index, qr/\.\.\/js\/plotly-2\.35\.2\.min\.js/, 'ui2 index preloads the existing generated Plotly bundle' );
like( $index, qr/js\/ui2\.js/, 'ui2 index loads the plain JavaScript playground' );
like( $index, qr/css\/ui2\.css/, 'ui2 index loads the ui2 stylesheet' );
like( $index, qr/react\/ui2-react\.css/, 'ui2 index loads the React workbench stylesheet' );
like( $index, qr/<html lang="en" data-ui2-theme="slate">/, 'ui2 index starts with Slate selected at the document root' );
like( $index, qr/<script type="module" src="react\/ui2-react\.js/, 'ui2 index loads the React workbench module' );
like( $index, qr/id="ui2-session-status"/, 'ui2 index exposes a session/project status target' );
like( $index, qr/data-app-id="ui2_views"/, 'ui2 index exposes the generated application id' );
like( $index, qr/Choose a menu group from the options on the left/, 'ui2 index opens at a neutral menu-group-first shell' );
like( $index, qr/module from the list that appears at the top of the page/, 'ui2 index describes the selected-menu module strip' );
unlike( $index, qr/<p class="ui2-kicker">Ready<\/p>/, 'ui2 empty shell does not show a Ready kicker' );
like( $index, qr/class="ui2-nav-icon-button" id="ui2-nav-toggle"/, 'ui2 menu toggle lives in the topbar instead of the collapsed sidebar column' );
like( $index, qr/<a class="ui2-title-link" href="\?apprun=1" target="_blank" rel="noopener" title="Open another [^"]+ instance">[\s\S]*?<h1>[^<]+<\/h1>[\s\S]*?<\/a>/, 'ui2 title opens another application instance like legacy' );
like( $index, qr/id="ui2-module-strip"/, 'ui2 index exposes a legacy-style selected menu module strip' );
like( $index, qr/id="ui2-feedback"/, 'ui2 index exposes the legacy feedback utility entry point' );
like( $index, qr/id="ui2-docs"/, 'ui2 index exposes the legacy docs entry point' );
like( $index, qr/id="ui2-docs-menu"/, 'ui2 index exposes a docs menu for contextual module documentation' );
like( $app_map_js, qr/generatedOn:\s*"Generated on /, 'ui2 app map carries the legacy generated-on splash metadata' );
like( $app_map_js, qr/genappRevision:\s*"GenApp /, 'ui2 app map carries the GenApp revision splash metadata' );
like( $app_map_js, qr/directives\.docsbaseurl = "docs"/, 'ui2 app map records docsbaseurl for the docs entry point' );
like( $app_map_js, qr/app\.help\.feedback = "Feedback help"/, 'ui2 app map records legacy feedback help text' );

my $ui2_js = read_file( File::Spec->catfile( $ui2, qw(js ui2.js) ) );
like( $ui2_js, qr/function moduleSubmitEndpoint\(\)/, 'ui2 runtime bridge declares a module submit endpoint helper' );
like( $ui2_js, qr/isReactWorkbenchView\(state\.view\) && renderReactMmc\(module, fields\)/, 'ui2 delegates modules to React only through explicit view metadata' );
like( $ui2_js, qr/function renderReactMmc\(module, fields\).*?createField:.*?renderField\(field, role\).*?submit:.*?submitModule\(form\)/s, 'MMC React bridge reuses canonical UI2 fields and submission' );
like( $ui2_js, qr/function resizeMmcOutputs\(\).*?resizePlotlyOutputWhenVisible\(output\).*?resizeNglStage\(output\._ui2NglStage\).*?refreshNglOutputFrame\(output\)/s, 'MMC result tabs resize existing Plotly and refresh active NGL frames' );
like( $ui2_js, qr/function resizeNglStage\(stage\).*?stage\.handleResize\?\.\(\).*?requestNglRender\(stage\)/s, 'MMC result tabs resize NGL stages through the shared helper' );
like( $ui2_js, qr/function plotlyLayoutForOutput\(output, sourceLayout\).*?plotlyFitMode\(output\) === "pane".*?delete layout\.width;.*?delete layout\.height;/s, 'MMC fitted Plotly layouts remove fixed producer dimensions' );
like( $ui2_js, qr/function plotlyFitMode\(output\).*?closest\?\.\("\[data-plot-fit\]"\)/s, 'dynamic Plotly children inherit their MMC pane-fit setting' );
like( $ui2_js, qr/function observeFitPlotlyOutput\(output\).*?new ResizeObserver.*?resizePlotlyOutputWhenVisible\(output\)/s, 'MMC fitted Plotly surfaces observe their actual container size' );
like( $ui2_js, qr/function releaseReactMmcField\(fieldNode\).*?disconnectPlotlyOutputObserver.*?Plotly\.purge/s, 'MMC React unmount cleans up Plotly resize observation and graph state' );
like( $ui2_js, qr/ui2:mmc-reattached.*?values: cloneUi2Value\(state\.values\)/s, 'MMC reattachment publishes the restored submitted-input snapshot' );

my $ui2_react_js = read_file( File::Spec->catfile( $ui2, qw(react ui2-react.js) ) );
my $ui2_react_css = read_file( File::Spec->catfile( $ui2, qw(react ui2-react.css) ) );
my $ui2_react_source = read_file( File::Spec->catfile( $repo_root, qw(languages ui2 react src MmcWorkbench.tsx) ) );
like( $ui2_react_js, qr/Submitted inputs/, 'React bundle contains the MMC submitted-input summary' );
like( $ui2_react_js, qr/results\?\.runtimeLog/, 'React bundle places the runtime log from view metadata' );
like( $ui2_react_js, qr/\.outputs\.map|outputs\.map|[A-Za-z]\.outputs\.map/, 'React bundle places declared module outputs from view tab metadata' );
like( $ui2_react_js, qr/Expand workspace/, 'React bundle contains the view-driven workspace expansion control' );
like( $ui2_react_js, qr/Restore split view/, 'React bundle contains an explicit expanded-workspace restore control' );
like( $ui2_react_source, qr/\{extraInputs\.length > 0.*?Additional inputs.*?\}\s*\{advancedSection/s, 'MMC places additional inputs before advanced input' );
like( $ui2_react_source, qr/tab\.fit === "pane" \|\| tab\.fit === "wide"/, 'MMC fits wide Plotly tabs to their allocated panel' );
like( $ui2_react_source, qr/node\.setAttribute\("data-plot-fit", "pane"\).*?node\.matches\('\[data-output-type="plotly"\]'\).*?data-plot-fit/s, 'MMC applies fit-to-pane to the field root and a direct Plotly output' );
like( $ui2_react_css, qr/\.ui2-mmc-grid/, 'React stylesheet contains the fixed MMC workbench grid' );
like( $ui2_react_css, qr/\.ui2-mmc-result-card \.ui2-output-plotly\{[^}]*overflow:hidden/, 'MMC fitted Plotly output suppresses internal scrollbars' );
like( $ui2_react_css, qr/\.ui2-mmc-react-workspace-expanded/, 'MMC expanded workspace styles are present' );
like( $ui2_react_css, qr/\.ui2-mmc-result-card \.ui2-ngl-frame-scrubber/, 'React stylesheet owns the streamed-frame scrubber dimensions' );
like( $ui2_js, qr/output\._ui2_ngl_scrubbing.*?pointerdown.*?pointerup/s, 'streamed-frame scrubber remains mounted while the user drags it' );
unlike( $ui2_js, qr/function ngl_stream_telemetry_label\(output\).*?last_dropped_reason.*?parts\.push/s, 'stream telemetry does not expose internal dropped-frame reasons to users' );
unlike( $ui2_js, qr/function ngl_frame_label\(frame, index\)\s*\{[^}]*milestone_percent/s, 'streamed-frame selection does not repeat trial progress percentage' );
like( $ui2_js, qr/function ngl_stream_telemetry_label\(output\).*?Rendered \$\{percent\}% of accepted structures/s, 'stream telemetry reports rendering coverage of accepted structures' );
like( $ui2_js, qr/function renderTabs\(inputCount, outputCount\)/, 'ui2 runtime keeps input/output jump tabs with counts' );
like( $ui2_js, qr/tabButton\("Inputs", inputCount, true, "ui2-input-section"\)/, 'ui2 input jump tab keeps its field count for accessibility' );
like( $ui2_js, qr/const button = el\("button", "ui2-tab", label\)/, 'ui2 jump tabs display labels without count text' );
unlike( $ui2_js, qr/header\.appendChild\(el\("span", "ui2-pill", `\$\{fields\.length\}`\)\)/, 'ui2 section headers do not duplicate input/output count pills' );
like( $ui2_js, qr/function initHoverHelp\(\)/, 'ui2 runtime initializes legacy hover help tooltips' );
like( $ui2_js, qr/initHoverHelp\(\);\s+setHelpEnabled\(true\);/s, 'ui2 runtime enables legacy hover help by default' );
like( $ui2_js, qr/function setHelpEnabled\(enabled\)/, 'ui2 runtime keeps hover help state explicit' );
like( $ui2_js, qr/function setHoverHelp\(node, help\)/, 'ui2 runtime records generated help text on hover targets' );
like( $ui2_js, qr/setHoverHelp\(button, menu\.help\)/, 'ui2 menu group buttons expose generated menu help' );
like( $ui2_js, qr/setHoverHelp\(item, module\.help\)/, 'ui2 module strip buttons expose generated module help' );
like( $ui2_js, qr/setHoverHelp\(label, field\.help\)/, 'ui2 field labels expose generated field help' );
like( $ui2_js, qr/setHoverHelp\(nodes\.feedback, help\.feedback/, 'ui2 feedback button exposes generated global help' );
like( $ui2_js, qr/setHoverHelp\(nodes\.docs, help\.docs/, 'ui2 docs button exposes generated global help' );
like( $ui2_js, qr/event\.target\?\.closest\?\.\("\[data-ui2-help\]"\)/, 'ui2 hover help delegates to generated help targets' );
like( $ui2_js, qr/function syncDocsLink\(\)/, 'ui2 runtime syncs the docs button from generated docsbaseurl' );
like( $ui2_js, qr/function docsModuleUrl\(/, 'ui2 runtime builds legacy-style per-module docs links' );
like( $ui2_js, qr/`\.\.\/\$\{base\}\/`/, 'ui2 runtime rebases relative docsbaseurl out of the ui2 directory' );
like( $ui2_js, qr/`\$\{mainUrl\}\$\{menu\}\/\$\{id\}\/\$\{id\}\.html`/, 'ui2 runtime mirrors SASSIE menu-scoped module docs path convention' );
like( $ui2_js, qr/nodes\.feedback\?\.addEventListener\("click", \(\) => openUtilityModule\("sys_feedback"\)\)/, 'ui2 feedback button opens the legacy feedback utility' );
like( $ui2_js, qr/dialogClass: \(moduleId === "sys_feedback" \|\| moduleId === "sys_feedback2"\) \? "ui2-feedback-dialog"/, 'ui2 feedback opens in a modal-sized utility dialog' );
like( $ui2_js, qr/function renderFeedbackTool\(module, fields\)/, 'ui2 runtime has a dedicated Feedback utility renderer' );
like( $ui2_js, qr/await submitUtilityModule\(form, module, `ajax\/sys_config\/\$\{moduleId\}\.php`/, 'ui2 feedback submits through the generated legacy feedback endpoint' );
like( $ui2_js, qr/function utilityAllowsAnonymous\(module\).*?sys_feedback/s, 'ui2 feedback can be submitted before login like legacy' );
like( $ui2_js, qr/function showLegacyMessagePayload\(payload, options = \{\}\)/, 'ui2 runtime handles legacy backend _message payloads' );
like( $ui2_js, qr/function legacyMessageFromPayload\(payload\).*?payload\._message/s, 'ui2 runtime maps legacy _message payloads into dialogs' );
like( $ui2_js, qr/function showLegacyMessageDialog\(message\).*?ui2-legacy-message-dialog/s, 'ui2 runtime renders backend messages as modal warnings' );
like( $ui2_js, qr/function sanitizeLegacyMessageHtml\(html\).*?querySelectorAll\("script, style, iframe, object, embed"\)/s, 'ui2 sanitizes legacy message HTML before rendering' );
like( $ui2_js, qr/if \(!choices\.length\).*?input\.name = field\.name \|\| field\.id/s, 'ui2 supports legacy individual radio fields without values arrays' );
like( $ui2_js, qr/input\.name = field\.name \|\| field\.id;\s+input\.value = choice\.value/s, 'ui2 grouped radio choices use the legacy field name when present' );
like( $ui2_js, qr/control\.type === "radio" && control\.dataset\.fieldName[\s\S]+return control\.dataset\.fieldName/s, 'ui2 utility radio submits use the legacy radio group name' );
like( $ui2_js, qr/if \(type === "job"\) \{\s*return renderJobReferenceControl\(field\);/s, 'ui2 renders legacy job reference fields with a dedicated control' );
like( $ui2_js, qr/function openJobReferenceDialog\(field, targetControl\)/, 'ui2 runtime opens a second modal chooser for reference jobs' );
like( $ui2_js, qr/function groupJobReferenceRows\(rows, columns\)/, 'ui2 reference job chooser groups jobs into a legacy-style tree' );
like( $ui2_js, qr/monthKey:\s*`\$\{year\}-\$\{month\}`/, 'ui2 reference job chooser groups top-level folders by year-month' );
like( $ui2_js, qr/dayKey:\s*`\$\{year\}-\$\{month\}-\$\{day\}`/, 'ui2 reference job chooser groups nested folders by day' );
like( $ui2_js, qr/function jobReferenceModule\(job, columns\)/, 'ui2 reference job chooser groups day folders by module' );
like( $ui2_js, qr/sort\(\(left, right\) => jobReferenceStartSeconds\(right, columns\) - jobReferenceStartSeconds\(left, columns\)\)/, 'ui2 reference job chooser sorts jobs newest first like legacy jstree' );
like( $ui2_js, qr/function jobReferenceTimeLabel\(job, columns\).*?getUTCHours\(\).*?UTC/s, 'ui2 reference job leaf labels use legacy UTC time-of-day text' );
like( $ui2_js, qr/\["hour", "Hour"\].*?\["day", "Day"\].*?\["week", "Week"\].*?\["month", "Month"\]/s, 'ui2 Job Manager completed filter offers legacy Hour Day Week Month windows' );
like( $ui2_js, qr/function completedFilterSeconds\(value\).*?hour:\s*60 \* 60.*?month:\s*30 \* 24 \* 60 \* 60/s, 'ui2 Job Manager maps completed windows to legacy time ranges' );
like( $ui2_js, qr/function completedFilterSeconds\(value\).*?legacyDays \* 24 \* 60 \* 60/s, 'ui2 Job Manager keeps old numeric day filters compatible' );
like( $ui2_js, qr/function renderJobActionsLegend\(\).*?Actions Legend.*?attach to job.*?attach to job in a new window.*?delete job.*?cancel job.*?clear lock/s, 'ui2 Job Manager renders a legacy-style actions legend' );
like( $ui2_js, qr/formData\.append\(input\.name, input\.value\)/, 'ui2 submits selected reference jobs through legacy *_altval array fields' );
like( $ui2_js, qr/function renderServerFileTree\(entries, container, options\)/, 'ui2 server file chooser uses a tree renderer' );
like( $ui2_js, qr/function renderServerFileTreeNode\(entry, options, depth\)/, 'ui2 server file chooser renders folder and file tree nodes' );
like( $ui2_js, qr/function serverFileTreeSelectable\(entry, mode\)/, 'ui2 server file chooser centralizes rfile/lrfile/rpath selectability' );
like( $ui2_js, qr/function renderFileManagerNameCell\(row, entry, depth, isFolder\)/, 'ui2 File Manager shares legacy-style file and folder row labeling' );
like( $ui2_js, qr/function isDynamicOutputField\(field\)/, 'ui2 runtime detects legacy dynamic output declarations' );
like( $ui2_js, qr/role === "output" && isDynamicOutputField\(field\).*?row\.hidden = true/s, 'ui2 dynamic output rows are hidden until runtime data arrives' );
like( $ui2_js, qr/function updateDynamicOutput\(group, payload\).*?const existing = new Map\(\).*?updateOutputElement\(output, item\.value\).*?existing\.forEach/s, 'ui2 dynamic output children reuse and retain normal output rendering' );
like( $ui2_js, qr/function clearRuntimeOutputs\(scope\).*?updateDynamicOutput\(output, \{ items: \[\] \}\).*?delete output\.dataset\.runtimeText/s, 'ui2 clears dynamic and textarea output state before a new submit' );
like( $ui2_js, qr/function renderNglOutputShell\(field, type\).*?_plot.*?_buttons/s, 'ui2 NGL outputs render the legacy plot and buttons shell' );
like( $ui2_js, qr/function renderNglOutput\(output, value\).*?new window\.NGL\.Stage\(plot\.id\).*?stage\.loadFile\(normalizeNglLoadName\(payload\.loadname\), payload\.loadparams/s, 'ui2 NGL outputs load rebased legacy NGL payloads into a stage' );
like( $ui2_js, qr/function normalizeNglLoadName\(loadname\).*?value\.startsWith\("results\/"\).*?`\.\.\/\$\{value\}`/s, 'ui2 NGL renderer rebases legacy result-relative paths from the ui2 directory' );
like( $ui2_js, qr/function ensureNglLoaded\(\).*?loadScript\("\.\.\/js\/ngl\.js"\)/s, 'ui2 NGL renderer reuses the generated legacy NGL bundle' );
like( $ui2_js, qr/const NGL_REPRESENTATION_TYPES = \[[\s\S]*"backbone"[\s\S]*"ball\+stick"[\s\S]*"cartoon"[\s\S]*"tube"[\s\S]*\]/, 'ui2 NGL renderer uses the legacy representation button list' );
like( $ui2_js, qr/function refreshSessionState\(\)/, 'ui2 runtime bridge declares a legacy session status helper' );
like( $ui2_js, qr/function legacyEndpoint\(paramName, path\)/, 'ui2 runtime bridge builds explicit legacy app-root endpoints' );
like( $ui2_js, qr/legacyEndpoint\("", "ajax"\)/, 'ui2 runtime bridge defaults submit endpoints to the legacy ajax root' );
like( $ui2_js, qr/dataset\.appId/, 'ui2 runtime bridge can fall back to the generated application id' );
like( $ui2_js, qr/sys_status\.php/, 'ui2 runtime bridge checks legacy sys_status for logon/project state' );
like( $ui2_js, qr/function openLoginDialog\(options = \{\}\)/, 'ui2 runtime bridge keeps login on the ui2 page' );
like( $ui2_js, qr/function openRegisterDialog\(\)/, 'ui2 runtime bridge keeps register on the ui2 page through the legacy sys_register module' );
like( $ui2_js, qr/function applyLoginDialogMode\(overlay, mandatory\)/, 'ui2 login dialog can switch between mandatory and dismissible modes' );
like( $ui2_js, qr/openLoginDialog\(\{ mandatory: true \}\)/, 'ui2 logged-out login action opens a mandatory login dialog' );
like( $ui2_js, qr/await openRegisterDialog\(\);/, 'ui2 splash register action opens a dedicated register dialog' );
like( $ui2_js, qr/await submitUtilityModule\(form, module, "ajax\/sys_config\/sys_register\.php"/, 'ui2 register dialog submits to the legacy register endpoint' );
like( $ui2_js, qr/function runLegacyCaptchaGate\(\)/, 'ui2 register dialog has a legacy captcha gate helper' );
like( $ui2_js, qr/ajax\/sys_config\/sys_captcha\.php/, 'ui2 register dialog requests legacy captcha challenges' );
like( $ui2_js, qr/ajax\/sys_config\/sys_captcha_verify\.php/, 'ui2 register dialog verifies captcha codes through the legacy endpoint' );
like( $ui2_js, qr/close\.hidden = mandatory/, 'ui2 mandatory login hides the dialog close control' );
like( $ui2_js, qr/cancel\.hidden = mandatory/, 'ui2 mandatory login hides the dialog cancel control' );
like( $ui2_js, qr/function openLogoffDialog\(\)/, 'ui2 logoff opens a confirmation dialog before calling the backend' );
like( $ui2_js, qr/el\("button", "ui2-button ui2-logoff-confirm", "Logoff"\)/, 'ui2 logoff confirmation includes an explicit Logoff button' );
like( $ui2_js, qr/sys_login\.php/, 'ui2 runtime bridge posts login to the legacy login endpoint' );
like( $ui2_js, qr/function parseJsonResponse\(response, label\)/, 'ui2 runtime bridge reports non-JSON backend responses with endpoint context' );
like( $ui2_js, qr/PHP source instead of executing it/, 'ui2 runtime bridge calls out PHP-disabled runtime hosts' );
like( $ui2_js, qr/function appTitle\(\)/, 'ui2 splash resolves the generated application title' );
like( $ui2_js, qr/docs\.href = "\.\.\/docs\/"/, 'ui2 splash documentation link resolves to the legacy app docs directory' );
like( $ui2_js, qr/function splashFooterLines\(\)/, 'ui2 splash derives footer metadata lines from generated app metadata' );
like( $ui2_js, qr/appMap\.generatedOn/, 'ui2 splash footer includes generated-on metadata when present' );
like( $ui2_js, qr/appMap\.genappRevision/, 'ui2 splash footer includes GenApp revision credit when present' );
like( $ui2_js, qr/function syncSplashForSession\(\)/, 'ui2 syncs the splash dialog from legacy session state' );
like( $ui2_js, qr/renderSessionState\(\);\s+syncSplashForSession\(\);/s, 'ui2 checks splash visibility after refreshing legacy session status' );
like( $ui2_js, qr/function showStartupShell\(\)/, 'ui2 startup can show the application shell without loading a module' );
like( $ui2_js, qr/Choose a menu group from the options on the left/, 'ui2 runtime reset uses the menu-group-first shell copy' );
unlike( $ui2_js, qr/<p class="ui2-kicker">Ready<\/p>/, 'ui2 runtime reset does not restore the Ready kicker' );
like( $ui2_js, qr/showStartupShell\(\);\s+return Promise\.resolve\(\);/s, 'ui2 startup does not auto-load the first generated module' );
unlike( $ui2_js, qr/function loadFirstAvailable\(\)/, 'ui2 no longer has a first-available-module startup path' );
like( $ui2_js, qr/function collapseMenuGroups\(\)/, 'ui2 startup can leave all menu groups closed' );
like( $ui2_js, qr/activeMenuId/, 'ui2 tracks the visible menu category separately from the loaded module' );
like( $ui2_js, qr/function renderModuleStrip\(\)/, 'ui2 renders selected menu modules outside the sidebar group cards' );
unlike( $ui2_js, qr/index === 0 \? "true" : "false"/, 'ui2 startup does not privilege the first menu group' );
like( $ui2_js, qr/function chooseMenuModule\(moduleId\)/, 'ui2 menu module selection uses a dedicated transition path' );
like( $ui2_js, qr/function selectMenuGroup\(menuId\)[\s\S]+clearLoadedModule\(\);[\s\S]+renderMenu\(\);/, 'ui2 menu group selection clears the loaded module while showing that group choices' );
like( $ui2_js, qr/function clearLoadedModule\(\)/, 'ui2 can blank the work area without returning to startup help' );
like( $ui2_js, qr/setSidebarCollapsed\(true, false\)/, 'ui2 collapses the menu only after a module is selected without persisting that state' );
like( $ui2_js, qr/function menuVisibleForSession\(menu\)/, 'ui2 menu rendering filters restricted menu groups using session state' );
like( $ui2_js, qr/function userConfigGroupVisible\(groupId, group\)/, 'ui2 Settings can hide deprecated user-configurable groups' );
like( $ui2_js, qr/groupId === "beta"/, 'ui2 Settings hides the legacy beta group checkbox' );
like( $ui2_js, qr/nodes\.navToggle\.setAttribute\("aria-label", label\)/, 'ui2 collapsed menu toggle updates accessible label without occupying the sidebar' );
like( $ui2_js, qr/function initWebSocket\(\)/, 'ui2 runtime bridge initializes the legacy websocket channel' );
like( $ui2_js, qr/ajax\/sys_uid\.php/, 'ui2 runtime bridge uses the legacy sys_uid endpoint for websocket discovery' );
like( $ui2_js, qr/new window\.ab\.Session/, 'ui2 runtime bridge uses the legacy Autobahn websocket session' );
like( $ui2_js, qr/function subscribeRuntimeMessages\(uuid\)/, 'ui2 runtime bridge can subscribe to a submitted job uuid' );
like( $ui2_js, qr/state\.ws\.conn\.subscribe\(uuid, handleWebSocketMessage\)/, 'ui2 runtime bridge wires websocket messages into the runtime handler' );
like( $ui2_js, qr/function handleWebSocketMessage\(topic, data\)/, 'ui2 runtime bridge receives websocket runtime chunks' );
like( $ui2_js, qr/applyRuntimePayload\(payload\)/, 'ui2 websocket chunks flow through the same output rendering path as polling' );
like( $ui2_js, qr/ui2-ws-indicator-ok/, 'ui2 runtime bridge updates the websocket footer indicator' );
like( $ui2_js, qr/function buildSubmitFormData\(form, uuid\)/, 'ui2 runtime bridge builds GenApp submit FormData explicitly' );
like( $ui2_js, qr/function appendSelectedFiles\(formData, form\)/, 'ui2 runtime bridge includes selected file payloads' );
like( $ui2_js, qr/function appendServerSelection\(formData, selection\)/, 'ui2 runtime bridge includes server file selections' );
like( $ui2_js, qr/sys_files\.php/, 'ui2 runtime bridge uses the legacy server file endpoint' );
like( $ui2_js, qr/formData\.set\(`_selaltval_\$\{selection\.id\}`/, 'ui2 server file selections include the legacy selected-alt marker' );
like( $ui2_js, qr/\$\{selection\.id\}_altval\[\]/, 'ui2 server file selections include legacy encoded alt values' );
like( $ui2_js, qr/event\.isTrusted/, 'ui2 server file replay does not clear restored selections with synthetic events' );
like( $ui2_js, qr/function renderJobManagerTool\(fields, moduleId = "sys_job_manager"\)/, 'ui2 has a dedicated Job Manager shell' );
unlike( $ui2_js, qr/function renderJobManagerTool\(fields, moduleId = "sys_job_manager"\).*?renderToolOutput\("Messages"/s, 'ui2 Job Manager does not render its unused messages textarea output' );
like( $ui2_js, qr/function fallbackUtilityModule\(moduleId\)/, 'ui2 can synthesize topbar utility modules not emitted into modules/' );
like( $ui2_js, qr/ajax\/sys_config\/sys_jobs2\.php/, 'ui2 Job Manager loads rows from the legacy details-capable jobs endpoint' );
like( $ui2_js, qr/function applyJobManagerFilters\(table\)/, 'ui2 Job Manager applies local table filters' );
like( $ui2_js, qr/function updateJobFilterChoices\(table, rows, columns\)/, 'ui2 Job Manager populates filter choices from loaded rows' );
like( $ui2_js, qr/function renderJobSelectFilter\(id, label, options\)/, 'ui2 Job Manager renders select filters for job columns' );
like( $ui2_js, qr/function toolFieldControl\(section, id, tagName\)/, 'ui2 Job Manager reads actual filter controls instead of wrapper rows' );
like( $ui2_js, qr/ajax\/sys_config\/sys_managejob\.php/, 'ui2 Job Manager uses the legacy manage-job endpoint for row actions' );
like( $ui2_js, qr/function submitSystemModuleAction\(action, jobIds, moduleId = "sys_job_manager"\)/, 'ui2 Job Manager can submit legacy system-module actions' );
like( $ui2_js, qr/applySavedJobInput\(pollUuid\)/, 'ui2 Job Manager explicitly restores saved inputs from the legacy switch target' );
like( $ui2_js, qr/startJobPolling\(\s*pollUuid, form, status, true, !restoredInput, false\)/s, 'ui2 Job Manager polls and replays the uuid from the legacy switch target after input restore' );
like( $ui2_js, qr/ajax\/ui2_job_input\.php/, 'ui2 Job Manager has a target-local saved input fallback endpoint' );
like( $ui2_js, qr/function moduleIdFromSwitchParts\(parts\)/, 'ui2 Job Manager parses legacy switch targets without assuming one shape' );
like( $ui2_js, qr/function applyInputPayload\(inputs, options = \{\}\)/, 'ui2 Job Manager can hydrate form inputs from reattached job payloads' );
like( $ui2_js, qr/function repeatIsCondition\(expression\)/, 'ui2 runtime detects expression-style repeat visibility conditions' );
like( $ui2_js, qr/function repeatConditionTokens\(expression\)/, 'ui2 runtime tokenizes expression-style repeat visibility conditions' );
like( $ui2_js, qr/function repeatConditionValue\(expression, rawValues, activeRows, rowsByFieldId\)/, 'ui2 runtime evaluates expression-style repeat visibility conditions' );
like( $ui2_js, qr/function repeatControllerId\(expression\).*?repeatIsCondition\(String\(expression\)\).*?return ""/s, 'ui2 repeater planning ignores expression repeat visibility gates' );
like( $ui2_js, qr/function conditionalRepeatDependencyIds\(scope\).*?repeatIsCondition\(expression\).*?repeatConditionDeps\(expression\)/s, 'ui2 replay dependency ordering includes expression repeat gates' );
like( $ui2_js, qr/function repeaterControllerIds\(\).*?isRepeater\(field\).*?ids\.add\(field\.id\)/s, 'ui2 replay dependency ordering includes repeater controllers' );
like( $ui2_js, qr/function applyInputPayload\(inputs, options = \{\}\).*?conditionalRepeatDependencyIds\(document\.getElementById\("ui2-form"\)\).*?repeaterControllerIds\(\).*?syncValues\(\).*?entries\.forEach/s, 'ui2 reattached input replay restores repeat dependencies before dependent values' );
like( $ui2_js, qr/function renderFileManagerTool\(module, fields\)/, 'ui2 has a dedicated File Manager shell' );
like( $ui2_js, qr/function downloadFileManagerSelection\(table, status, links, module\)/, 'ui2 File Manager submits selected files for download and renders returned links' );
like( $ui2_js, qr/function renderUserConfigTool\(module, fields\)/, 'ui2 has a dedicated Settings shell' );
like( $ui2_js, qr/afterSuccess: \(\) => setSessionProjectFromSettings\(form\)/, 'ui2 Settings updates the legacy session project after submit' );
like( $ui2_js, qr/function renderRegisterTool\(module, fields\)/, 'ui2 has a dedicated Register shell' );
like( $ui2_js, qr/function legacyUtilityFieldName\(control\)/, 'ui2 Settings submits legacy repeat-prefixed field names' );
like( $ui2_js, qr/function userConfigFields\(fields\)/, 'ui2 Settings filters fields through legacy directive visibility' );
like( $ui2_js, qr/LEGACY_USER_CONFIG_THEME_FIELD_IDS = new Set\(\["changetheme", "themetype", "themedark", "themelight", "theme"\]\)/, 'ui2 Settings recognizes the legacy theme control cluster' );
like( $ui2_js, qr/function ui2UserConfigFields\(fields\).*?ui2ThemeConfigField\(\)/s, 'ui2 Settings replaces legacy theme controls with a native UI2 theme preference' );
like( $ui2_js, qr/\["superhero", "Superhero"\][\s\S]+\["flatly", "Flatly"\]/, 'ui2 Settings exposes legacy-inspired theme candidates for review' );
like( $ui2_js, qr/dataset\.ui2LocalPreference = "theme"/, 'ui2 Settings marks the native theme selector as a local preference' );
like( $ui2_js, qr/control\.dataset\.ui2LocalPreference[\s\S]+return;/, 'ui2 Settings keeps native UI2 preferences out of legacy settings submits' );
like( $ui2_js, qr/function renderGroupField\(field\)/, 'ui2 Settings renders legacy group fields as configured checkboxes' );
like( $ui2_js, qr/control\.type === "checkbox" && !control\.checked[\s\S]+return;/, 'ui2 utility submit skips unchecked checkboxes like native legacy forms' );
like( $ui2_js, qr/dataset\.pullKey = field\.pull/, 'ui2 Settings records legacy pull keys separately from field ids' );
like( $ui2_js, qr/function replaceSelectOptions\(select, values\)/, 'ui2 Settings rebuilds pulled listbox options from legacy array payloads' );
like( $ui2_js, qr/function setLegacyProject\(project\).*?sys_project\.php/s, 'ui2 Settings uses the legacy project session endpoint' );
like( $ui2_js, qr/fieldControls\(form\)[\s\S]+dataset\.pullKey[\s\S]+sys_pull\.php/s, 'ui2 Settings pulls only fields declared with legacy pull metadata' );
like( $ui2_js, qr/function fieldControls\(scope\)/, 'ui2 runtime scans actual form controls instead of field wrapper rows' );
like( $ui2_js, qr/parts\.unshift\(expected\)[\s\S]+parts\.unshift\(parent\)/, 'ui2 Settings preserves legacy nested repeat field names' );
like( $ui2_js, qr/form\.noValidate = true/, 'ui2 Settings uses inline validation inside the modal instead of browser-native validation bubbles' );
like( $ui2_js, qr/function validateUtilityForm\(form\)/, 'ui2 Settings validates active utility controls before submit' );
like( $ui2_js, qr/function validateMatchedUtilityControls\(form\)/, 'ui2 utility validation checks repeated email and password fields that must match' );
like( $ui2_js, qr/await refreshSessionState\(\);\s+await pullUtilityFieldValues\(form\);/s, 'ui2 Settings refreshes pulled project choices after a successful update' );
like( $ui2_js, qr/function normalizeUserConfigField\(field\)/, 'ui2 Settings can apply legacy system-tool field exceptions' );
like( $ui2_js, qr/id === "newprojectdesc"[\s\S]+required: "false"/, 'ui2 Settings keeps new project descriptions optional like legacy' );
like( $ui2_js, qr/control\.pattern = field\.pattern/, 'ui2 Settings carries module regex patterns onto generated controls' );
unlike( $ui2_js, qr/document\.createTextNode\([^)]*Optional/, 'ui2 switches do not render generic Optional text' );
like( $ui2_js, qr/formData\.append\("selectedfiles\[\]", id\)/, 'ui2 File Manager sends legacy encoded selected file ids' );
like( $ui2_js, qr/const uuid = createUuid\(\);\s+formData\.set\("_uuid", uuid\)/s, 'ui2 File Manager supplies reusable uuid metadata to the generated wrapper' );
like( $ui2_js, qr/waitForFileManagerResult\(uuid, status\)/, 'ui2 File Manager polls async system download jobs with the submitted uuid' );
like( $ui2_js, qr/formData\.set\("_docrootexecutable", fileManagerModule\.docrootexecutable\)/, 'ui2 File Manager sends docroot executable metadata for system downloads' );
like( $ui2_js, qr/ajax\/sys_config\/sys_pull\.php[\s\S]+url\.searchParams\.set\("datetime", "0"\)/, 'ui2 system utility serverdate fields use the legacy datetime pull endpoint' );
like( $ui2_js, qr/function normalizeFileList\(value\)/, 'ui2 File Manager normalizes backend download file payload shapes' );
like( $ui2_js, qr/no downloadable file link was returned/, 'ui2 File Manager does not report success without a returned link' );
like( $ui2_js, qr/const uuid = createUuid\(\)/, 'ui2 runtime bridge keeps the submitted uuid for job polling' );
like( $ui2_js, qr/formData\.set\("_uuid", uuid/, 'ui2 runtime bridge supplies uuid for generated backend submit path' );
like( $ui2_js, qr/formData\.set\("_logon", state\.session\.logon/, 'ui2 submit uses the legacy session logon' );
like( $ui2_js, qr/formData\.set\("_project", state\.session\.project/, 'ui2 submit uses the legacy session project' );
like( $ui2_js, qr/if \(state\.module\?\.docrootexecutable\).*?formData\.set\("_docrootexecutable", state\.module\.docrootexecutable\)/s, 'ui2 runtime bridge sends legacy docroot executable metadata for system module submits' );
like( $ui2_js, qr/const payload = await parseJsonResponse\(response, "Runtime"\);\s+state\.submitResponse = payload;\s+showLegacyMessagePayload\(payload\);/s, 'ui2 shows legacy submit messages before failed runtime responses become inline errors' );
like( $ui2_js, qr/function startJobPolling\(\s*uuid, form, statusNode, getLastMsg = true, getInput = false,\s*subscribeFirst = true\)/s, 'ui2 runtime bridge starts polling submitted jobs' );
like( $ui2_js, qr/startJobPolling\(\s*pollUuid, form, status, true, !restoredInput, false\)/s, 'ui2 reattachment hydrates the replay journal before subscribing to live events' );
like( $ui2_js, qr/function pollJobResults\(uuid, form, statusNode, lastDelay, getLastMsg, getInput = false\)/, 'ui2 runtime bridge polls legacy job results' );
like( $ui2_js, qr/ajax\/get_results\.php/, 'ui2 runtime bridge uses the legacy job results endpoint' );
like( $ui2_js, qr/url\.searchParams\.set\("_getlastmsg", getLastMsg \? "1" : "0"\)/, 'ui2 runtime bridge requests legacy last-message updates with the PHP-native flag' );
like( $ui2_js, qr/url\.searchParams\.set\("_getinput", getInput \? "true" : "false"\)/, 'ui2 runtime bridge requests saved job inputs only when reattaching' );
like( $ui2_js, qr/const payload = await parseJsonResponse\(response, "Job results"\);\s+state\.submitResponse = payload;\s+showLegacyMessagePayload\(payload\);/s, 'ui2 shows legacy polling messages from job result payloads' );
like( $ui2_js, qr/function applyRuntimePayload\(payload\)/, 'ui2 runtime bridge maps runtime payloads into rendered outputs' );
like( $ui2_js, qr/function applyRuntimePayload\(payload\).*?showLegacyMessagePayload\(payload\);/s, 'ui2 runtime payload rendering preserves legacy backend message popups' );
like( $ui2_js, qr/function mergeRuntimeText\(existing, incoming\)/, 'ui2 runtime bridge preserves accumulated runtime text output' );
like( $ui2_js, qr/function isCompleteRuntimeText\(text\)/, 'ui2 runtime bridge recognizes complete final textarea streams' );
like( $ui2_js, qr/function stripUi2RuntimeStatus\(text\)/, 'ui2 runtime bridge strips ui2-only runtime status text from canonical output' );
like( $ui2_js, qr/function isRuntimeDividerText\(text\)/, 'ui2 runtime bridge preserves repeated textarea divider lines' );
like( $ui2_js, qr/output\.dataset\.runtimeText = merged/, 'ui2 runtime bridge keeps runtime text across later output redraws' );
like( $ui2_js, qr/function renderPlotlyOutput\(output, value\)/, 'ui2 runtime bridge has a dedicated Plotly output renderer' );
like( $ui2_js, qr/Plotly\.react\(output, figure\.data, layout, config\)/, 'ui2 authoritative plot snapshots update the existing Plotly graph' );
like( $ui2_js, qr/Plotly\.extendTraces\(output, \{ x, y \}, indices/, 'ui2 plot append events extend existing traces incrementally' );
like( $ui2_js, qr/function applyPlotlyModebarHooks\(figure, config\)/, 'ui2 runtime bridge honors legacy Plotly Chart Editor config' );
like( $ui2_js, qr/Edit in Chart Editor/, 'ui2 Plotly modebar exposes the Chart Editor action when configured' );
like( $ui2_js, qr/function chartEditorLayout\(layout\)/, 'ui2 Plotly Chart Editor receives an editor-friendly layout copy' );
like( $ui2_js, qr/function chartEditorUrl\(editorUrl, id\)/, 'ui2 Plotly Chart Editor URLs resolve through the legacy app root' );
like( $ui2_js, qr/new URL\(legacyEndpoint\("", raw\), window\.location\.href\)/, 'ui2 relative Chart Editor URLs do not resolve under the ui2 subdirectory' );
like( $ui2_js, qr/function parsePlotlyFigure\(value\)/, 'ui2 runtime bridge parses Plotly JSON string payloads' );
like( $ui2_js, qr/function defaultPlotlyLayout\(\)/, 'ui2 runtime bridge supplies default Plotly layout polish' );
like( $ui2_js, qr/function nglRepresentationStoreKey\(spec, index, layered\).*?layered \? nglRepresentationKey\(spec, index\) : spec\?\.type/s, 'ui2 NGL keeps simple payloads on generic button keys while layering named representations' );
like( $ui2_js, qr/function apply_ngl_coordinate_frame\(output, frame\).*?structure\.updatePosition\(frame\.coordinates\).*?updateRepresentations\(\{ position: true \}\)/s, 'ui2 NGL structure events update coordinates without recreating topology' );
like( $ui2_js, qr/function schedule_ngl_coordinate_frame\(output\).*?requestAnimationFrame.*?_ui2_ngl_pending_frame/s, 'ui2 NGL coalesces live coordinate frames to browser repaint cadence' );
like( $ui2_js, qr/formData\.set\("_runtime_protocol", "1"\).*?"job-events".*?"plot-append".*?"structure-frames"/s, 'ui2 advertises the versioned streaming capabilities explicitly' );
like( $ui2_js, qr/function applyPlotlyTheme\(layout\).*?plotlyLegendKeys\(layout\)\.forEach.*?contrastTextColor\(legendBackground\)/s, 'ui2 runtime bridge applies theme-aware Plotly legend contrast polish across multiple legend slots' );
like( $ui2_js, qr/function applyPlotlyTheme\(layout\).*?layout\.annotations = layout\.annotations\.map.*?contrastTextColor\(annotation\.bgcolor\)/s, 'ui2 runtime bridge applies theme-aware Plotly contrast to annotation legends' );
like( $ui2_js, qr/function plotlyThemeColors\(\).*?legendBackground: dark \? "rgba\(26, 32, 31, 0\.88\)" : "rgba\(255, 255, 255, 0\.88\)"/s, 'ui2 runtime bridge derives dark and light Plotly legend backgrounds' );
like( $ui2_js, qr/function contrastTextColor\(background\)/, 'ui2 runtime bridge derives readable Plotly legend text from the legend background' );
like( $ui2_js, qr/function plotlyLegendKeys\(layout\).*?\^legend\\d\*\$/s, 'ui2 runtime bridge detects legend, legend2, legend3, and later Plotly legend keys' );
like( $ui2_js, qr/function ensurePlotlyLoaded\(\)/, 'ui2 runtime bridge can load the existing generated Plotly asset' );
like( $ui2_js, qr/function normalizeProgressValue\(value\)/, 'ui2 runtime bridge normalizes progress payload values' );
like( $ui2_js, qr/window\.GenAppUi2TestHooks/, 'ui2 runtime exposes opt-in test hooks for behavior checks' );
like( $ui2_js, qr/function renderSubmitResponse\(payload\) \{\s+if \(!devMode\) \{\s+return;/, 'ui2 hides raw submit payloads outside dev mode' );
like( $ui2_js, qr/type === "float"[\s\S]+input\.step = "any"/, 'ui2 float inputs allow decimal values' );
like( $ui2_js, qr/type === "integer"[\s\S]+input\.step = "1"/, 'ui2 integer inputs keep whole-number stepping' );

my $ui2_css = read_file( File::Spec->catfile( $ui2, qw(css ui2.css) ) );
like( $ui2_css, qr/:root\[data-ui2-theme="system"\]/, 'ui2 stylesheet declares an explicit native system theme mode' );
like( $ui2_css, qr/:root\[data-ui2-theme="slate"\]/, 'ui2 stylesheet declares the Slate legacy-continuity theme mode' );
like( $ui2_css, qr/:root\[data-ui2-theme="dark"\]/, 'ui2 stylesheet declares an explicit native dark theme mode' );
like( $ui2_css, qr/:root\[data-ui2-theme="cyborg"\]/, 'ui2 stylesheet declares legacy-inspired dark review palettes' );
like( $ui2_css, qr/:root\[data-ui2-theme="flatly"\]/, 'ui2 stylesheet declares legacy-inspired light review palettes' );
like( $ui2_css, qr/--ui2-on-accent:/, 'ui2 stylesheet exposes a semantic foreground token for accent buttons' );
like( $ui2_css, qr/--ui2-focus-ring:/, 'ui2 stylesheet exposes a semantic focus-ring token' );
like( $ui2_css, qr/\.ui2-dialog-overlay/, 'ui2 stylesheet includes login dialog shell styles' );
like( $ui2_css, qr/\.ui2-legacy-message-dialog/, 'ui2 stylesheet includes legacy backend message dialog styles' );
like( $ui2_css, qr/\.ui2-legacy-message-icon/, 'ui2 stylesheet includes legacy backend message icon styling' );
like( $ui2_css, qr/\.ui2-captcha-dialog/, 'ui2 stylesheet includes a dedicated captcha dialog shell' );
like( $ui2_css, qr/\.ui2-splash-footer/, 'ui2 stylesheet includes splash footer metadata styles' );
like( $ui2_css, qr/\.ui2-output-plotly/, 'ui2 stylesheet includes a stable Plotly output surface' );
like( $ui2_css, qr/\.ui2-output-ngl\s*\{[^}]*white-space:\s*normal/s, 'ui2 stylesheet gives NGL outputs a non-text viewer container' );
like( $ui2_css, qr/\.ui2-ngl-button\[aria-pressed="true"\]/, 'ui2 stylesheet makes active NGL layer buttons visible' );
like( $ui2_css, qr/\.ui2-dynamic-output\s*\{[^}]*display:\s*grid/s, 'ui2 stylesheet stacks dynamic output instances' );
like( $ui2_css, qr/\.ui2-field\[hidden\],[\s\n]*\.ui2-dynamic-output-row\[hidden\]\s*\{[^}]*display:\s*none !important/s, 'ui2 stylesheet really hides inactive dynamic output rows' );
like( $ui2_css, qr/\.ui2-output-rendered/, 'ui2 stylesheet distinguishes rendered runtime output from placeholders' );
like( $ui2_css, qr/\.ui2-output-field/, 'ui2 stylesheet lets output rows use the full default width' );
like( $ui2_css, qr/\.ui2-mini-button/, 'ui2 stylesheet includes compact system action buttons' );
like( $ui2_css, qr/\.ui2-title-link/, 'ui2 stylesheet preserves clickable title styling' );
like( $ui2_css, qr/\.ui2-job-actions-legend/, 'ui2 stylesheet includes Job Manager actions legend styling' );
like( $ui2_css, qr/\.ui2-server-file-tree/, 'ui2 stylesheet includes a legacy-style server file tree' );
like( $ui2_css, qr/\.ui2-server-tree-checkbox/, 'ui2 stylesheet includes selectable server tree checkbox affordances' );
like( $ui2_css, qr/\.ui2-server-tree-icon-folder/, 'ui2 stylesheet distinguishes server folders from files' );
like( $ui2_css, qr/\.ui2-file-disclosure/, 'ui2 stylesheet includes File Manager disclosure controls' );
like( $ui2_css, qr/\.ui2-file-download-links/, 'ui2 stylesheet makes File Manager download links visible beside actions' );
like( $ui2_css, qr/\.ui2-module-strip\[hidden\]\s*\{\s*display:\s*none;/s, 'ui2 stylesheet honors hidden module choice strips' );
like( $ui2_css, qr/\.ui2-strip-module-button/, 'ui2 stylesheet includes selected menu module strip buttons' );
like( $ui2_css, qr/\.ui2-hover-help/, 'ui2 stylesheet includes hover help tooltip styling' );
like( $ui2_css, qr/body:not\(\.ui2-help-enabled\) \.ui2-hover-help/, 'ui2 stylesheet hides hover help while help mode is off' );
like( $ui2_css, qr/\.ui2-help-enabled \[data-ui2-help\]/, 'ui2 stylesheet marks generated hover help targets when help mode is on' );

my $app_map = read_file( File::Spec->catfile( $ui2, qw(js app-map.js) ) );
like( $app_map, qr/addMenuFromParts\("demo", "Demo", ""\)/, 'ui2 app map records menu groups' );
like( $app_map, qr/setMenuHelp\("demo", "Demo menu help"\)/, 'ui2 app map records menu group help' );
like( $app_map, qr/setMenuRestricted\("demo", "admin"\)/, 'ui2 app map records restricted menu groups' );
like( $app_map, qr/addModule\("demo", \{\s+id: "shared",\s+label: "Shared"\s+,help: "Shared module help"/, 'ui2 app map records menu module help' );
like( $app_map, qr/directives: \{\}/, 'ui2 app map initializes the legacy directive registry' );
like( $app_map, qr/directives\.usertheme = "true"/, 'ui2 app map records enabled legacy directives for hideifnot fields' );

my $shared = decode_json( read_file( File::Spec->catfile( $ui2, qw(modules shared.json) ) ) );
is( $shared->{module}, 'shared', 'shared summary records module id' );
is( $shared->{modulejson}{label}, 'UI2 Module Override', 'ui2/module_overrides replaces the canonical module for ui2' );
is( $shared->{modulejson}{executable}, 'ui2_module_override_shared', 'ui2/module_overrides executable is used' );
is( $shared->{modulejson}{fields}[0]{id}, 'ui2_override_input', 'ui2/module_overrides field is used' );
unlike( $shared->{modulejson}{label}, qr/Legacy UI2 Modules Override Should Lose/, 'ui2/module_overrides wins over ui2/modules fallback' );

is( $shared->{viewjson}{module}, 'shared', 'general view file is loaded' );
is( $shared->{viewjson}{labels}{basis}, 'target neutral', 'general view nested data is preserved' );
is( $shared->{viewjson}{labels}{title}, 'UI2 View', 'target-specific ui2 view overrides general view data' );
is( $shared->{viewjson}{renderers}{shared_input}, 'compact', 'target-specific ui2 view adds target-only data' );
is( $shared->{viewjson}{sections}[0]{id}, 'general', 'general view sections are available to ui2' );

my $plain = decode_json( read_file( File::Spec->catfile( $ui2, qw(modules plain.json) ) ) );
is( $plain->{module}, 'plain', 'plain summary records module id' );
is( $plain->{modulejson}{label}, 'Plain UI2 Modules Fallback', 'ui2/modules remains a fallback module override path' );
is( $plain->{modulejson}{fields}[0]{id}, 'plain_ui2_modules_input', 'ui2/modules fallback field is used when module_overrides is absent' );
is( $plain->{modulejson}{fields}[0]{help}, 'Plain input help', 'ui2 module summaries preserve legacy field help text' );
is_deeply( $plain->{viewjson}, {}, 'missing view files produce an empty view object' );

my $settings = decode_json( read_file( File::Spec->catfile( $ui2, qw(modules sys_user_config.json) ) ) );
is( $settings->{module}, 'sys_user_config', 'settings summary records system module id' );
ok( scalar @{ $settings->{modulejson}{fields} || [] }, 'settings summary preserves system module fields' );

my $file_manager = decode_json( read_file( File::Spec->catfile( $ui2, qw(modules sys_file_manager.json) ) ) );
is( $file_manager->{module}, 'sys_file_manager', 'file manager summary records configbase module id' );
ok( scalar @{ $file_manager->{modulejson}{fields} || [] }, 'file manager summary preserves configbase module fields' );

my $feedback = decode_json( read_file( File::Spec->catfile( $ui2, qw(modules sys_feedback.json) ) ) );
is( $feedback->{module}, 'sys_feedback', 'feedback summary records system module id' );
ok( scalar @{ $feedback->{modulejson}{fields} || [] }, 'feedback summary preserves system module fields' );
ok( scalar( grep { ($_->{type} || '') eq 'radio' && ($_->{name} || '') eq 'level' } @{ $feedback->{modulejson}{fields} || [] } ), 'feedback summary preserves legacy individual radio field group names' );

my $typed = decode_json( read_file( File::Spec->catfile( $ui2, qw(modules typed.json) ) ) );
is( $typed->{module}, 'typed', 'typed summary records module id' );
is( $typed->{modulejson}{fields}[0]{type}, 'integer', 'ui2 can carry integer fields without ui2 type templates' );
is( $typed->{modulejson}{fields}[1]{type}, 'checkbox', 'ui2 can carry checkbox fields without ui2 type templates' );
is( $typed->{modulejson}{fields}[2]{type}, 'float', 'ui2 can carry float fields without ui2 type templates' );
is( $typed->{modulejson}{fields}[3]{default}[0], '{"rot": [[[1.0, 0.0, 0.0]]], "trans": [[0.0, 0.0, 0.0]]}', 'ui2 module summaries preserve nested JSON string defaults as valid JSON' );
is( $typed->{modulejson}{fields}[8]{type}, 'integerpair', 'ui2 can carry integerpair matrix controllers without ui2 type templates' );
is( $typed->{modulejson}{fields}[8]{calc}, 'row_count,column_count', 'ui2 preserves integerpair matrix dimensions' );
is( $typed->{modulejson}{fields}[8]{headers}{row}[0], 'row_label', 'ui2 preserves matrix row header metadata' );
is( $typed->{modulejson}{fields}[9]{default}[1][1], '4', 'ui2 preserves matrix field two-dimensional defaults' );
is_deeply( $typed->{viewjson}, {}, 'typed module missing view files produce an empty view object' );

my $invalid = generate_fixture_app(
    repo_root    => $repo_root,
    fixture_name => 'ui2_invalid_view',
    test_dir     => File::Spec->catdir( $FindBin::Bin, '..' ),
);

isnt( $invalid->{status}, 0, 'invalid ui2 view JSON fails generation' );
like( $invalid->{output}, qr/JSON Error in view file views\/shared\.json/, 'invalid ui2 view JSON reports the view file path' );

done_testing();
