#!/usr/bin/env python3
"""Serve the NGL viewer lab plus synthetic coordinate-stream endpoints."""

from __future__ import annotations

import argparse
import json
import math
import os
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import parse_qs, urlparse


TOPOLOGY_FILES = {
    "hiv1_gag": "t/ngl_viewer_lab/fixtures/hiv1_gag_charmm27.pdb",
    "hiv1_gag_reduced": "t/ngl_viewer_lab/fixtures/hiv1_gag_charmm27_reduced_ca_p.pdb",
}
TOPOLOGY_COORDINATES = {}


def bounded_int(values, default, minimum, maximum):
    try:
        value = int(values[0])
    except (TypeError, ValueError, IndexError):
        value = default
    return max(minimum, min(maximum, value))


def topology_coordinates(topology):
    if not topology:
        return None
    if topology in TOPOLOGY_COORDINATES:
        return TOPOLOGY_COORDINATES[topology]
    filename = TOPOLOGY_FILES.get(topology)
    if not filename:
        return None
    coordinates = []
    with open(filename, "r", encoding="utf-8") as handle:
        for line in handle:
            if line.startswith(("ATOM", "HETATM")):
                coordinates.append((
                    float(line[30:38]),
                    float(line[38:46]),
                    float(line[46:54]),
                ))
    TOPOLOGY_COORDINATES[topology] = coordinates
    return coordinates


def atom_coordinates(atom_count, frame):
    phase = frame * 0.17
    for index in range(atom_count):
        chain = index // 9999
        residue = index % 9999
        x = (residue % 100) * 3.8
        y = ((residue // 100) % 100) * 3.8
        z = chain * 18.0 + (residue % 17) * 0.35
        if frame:
            x += math.sin(index * 0.013 + phase) * 1.5
            y += math.cos(index * 0.011 + phase) * 1.5
            z += math.sin(index * 0.007 + phase) * 0.9
        yield x, y, z


def displaced_coordinates(coordinates, frame):
    phase = frame * 0.17
    for index, (x, y, z) in enumerate(coordinates):
        yield (
            x + math.sin(index * 0.013 + phase) * 1.5,
            y + math.cos(index * 0.011 + phase) * 1.5,
            z + math.sin(index * 0.007 + phase) * 0.9,
        )


def pdb_text(atom_count):
    lines = [
        "REMARK synthetic CA-only benchmark structure",
        "REMARK generated by t/ngl_viewer_lab/stream_server.py",
    ]
    for index, (x, y, z) in enumerate(atom_coordinates(atom_count, 0), start=1):
        serial = ((index - 1) % 99999) + 1
        residue = ((index - 1) % 9999) + 1
        chain = chr(ord("A") + ((index - 1) // 9999) % 26)
        lines.append(
            "ATOM  %5d  CA  ALA %1s%4d    %8.3f%8.3f%8.3f  1.00 20.00           C"
            % (serial, chain, residue, x, y, z)
        )
    lines.append("END")
    return "\n".join(lines) + "\n"


def frame_values(atom_count, frame, topology=None):
    coordinates = topology_coordinates(topology)
    if coordinates is not None:
        atom_count = len(coordinates)
        source = displaced_coordinates(coordinates, frame)
    else:
        source = atom_coordinates(atom_count, frame)
    values = []
    for x, y, z in source:
        values.extend((x, y, z))
    return values


def frame_binary(atom_count, frame, topology=None):
    import array

    values = array.array("f", frame_values(atom_count, frame, topology))
    if values.itemsize != 4:
        raise RuntimeError("expected 32-bit float array support")
    return values.tobytes()


class StreamHandler(SimpleHTTPRequestHandler):
    server_version = "NglStreamLab/0.1"

    def end_headers(self):
        self.send_header("Access-Control-Allow-Origin", "*")
        self.send_header("Cache-Control", "no-store")
        super().end_headers()

    def do_GET(self):
        parsed = urlparse(self.path)
        params = parse_qs(parsed.query)
        if parsed.path == "/js/ngl.js":
            self.path = "/languages/html5/add/js/ngl.js"
            return super().do_GET()
        if parsed.path == "/stream/pdb":
            atoms = bounded_int(params.get("atoms"), 6730, 1, 250000)
            self.write_bytes(pdb_text(atoms).encode("utf-8"), "chemical/x-pdb")
            return
        if parsed.path == "/stream/frame.json":
            atoms = bounded_int(params.get("atoms"), 6730, 1, 250000)
            frame = bounded_int(params.get("frame"), 1, 0, 1000000)
            topology = (params.get("topology") or [""])[0]
            topology_atoms = topology_coordinates(topology)
            if topology_atoms is not None:
                atoms = len(topology_atoms)
            payload = {
                "atomCount": atoms,
                "frame": frame,
                "coordinateDtype": "float32",
                "coordinates": frame_values(atoms, frame, topology),
            }
            body = json.dumps(payload, separators=(",", ":")).encode("utf-8")
            self.write_bytes(body, "application/json")
            return
        if parsed.path == "/stream/frame.bin":
            atoms = bounded_int(params.get("atoms"), 6730, 1, 250000)
            frame = bounded_int(params.get("frame"), 1, 0, 1000000)
            topology = (params.get("topology") or [""])[0]
            topology_atoms = topology_coordinates(topology)
            if topology_atoms is not None:
                atoms = len(topology_atoms)
            self.send_response(200)
            self.send_header("Content-Type", "application/octet-stream")
            self.send_header("X-Atom-Count", str(atoms))
            self.send_header("X-Frame", str(frame))
            self.end_headers()
            self.wfile.write(frame_binary(atoms, frame, topology))
            return
        super().do_GET()

    def write_bytes(self, body, content_type):
        self.send_response(200)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    parser.add_argument(
        "--root",
        default=os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")),
        help="repository root to serve",
    )
    args = parser.parse_args()
    os.chdir(args.root)
    server = ThreadingHTTPServer((args.host, args.port), StreamHandler)
    print("serving http://%s:%d/t/ngl_viewer_lab/" % (args.host, args.port), flush=True)
    server.serve_forever()


if __name__ == "__main__":
    main()
