#!/usr/bin/env perl
use strict;
use warnings;

use Cwd qw(abs_path);
use File::Spec;
use FindBin;
use Getopt::Long qw(GetOptions);

use lib File::Spec->catdir( $FindBin::Bin, '..', 't', 'lib' );
use GenAppTest qw(find_executable repo_root run_command);

my @requested;
my $include_vendor = 0;
my $report_path;
my $help = 0;
GetOptions(
    'php=s@'          => \@requested,
    'include-vendor!' => \$include_vendor,
    'report=s'        => \$report_path,
    'help'            => \$help,
) or usage(2);
usage(0) if $help;

if ( !@requested && defined $ENV{GENAPP_PHP_BINARIES} ) {
    @requested = grep { $_ ne q{} } split /,/, $ENV{GENAPP_PHP_BINARIES};
}
push @requested, $ENV{PHP} if !@requested && defined $ENV{PHP} && $ENV{PHP} ne q{};
push @requested, 'php' if !@requested;

my @interpreters;
for my $requested (@requested) {
    my $path = find_executable($requested);
    die "requested PHP executable '$requested' is not executable\n" if !$path;
    push @interpreters, $path if !grep { $_ eq $path } @interpreters;
}

my $root = repo_root( File::Spec->catdir( $FindBin::Bin, '..', 't' ) );
my @tests = qw(
    t/html5_php_templates.t
    t/html5_backend_contract.t
    t/html5_action_button.t
    t/job_event_cache.t
    t/submission_upload_cleanup.t
    t/unit_tests/html5_mixed_file_selection.t
    t/html5_password_reset.t
    t/unit_tests/html5_language_overrides.t
    t/php_generated_compatibility.t
    t/php_vendor_compatibility.t
);

my @report = (
    '# GenApp PHP compatibility report',
    q{},
    'Generated by `tools/run_php_compatibility.pl`.',
    q{},
    '| PHP | Result | Tests | Bundled dependency pass |',
    '| --- | --- | --- | --- |',
);
my @details;
my $overall = 0;

for my $php (@interpreters) {
    my ( $version_status, $version ) = run_command(
        cwd => $root,
        cmd => [ $php, '-r', 'echo PHP_VERSION;' ],
    );
    die "could not read PHP version from '$php': $version\n" if $version_status != 0;

    my ( $module_status, $modules ) = run_command(
        cwd => $root,
        cmd => [ $php, '-m' ],
    );
    die "could not read PHP modules from '$php': $modules\n" if $module_status != 0;
    my @modules = grep { /^[A-Za-z0-9_]+\z/ } split /\R/, $modules;

    my %env = ( PHP => $php );
    $env{GENAPP_PHP_VENDOR_FULL} = 1 if $include_vendor;
    my ( $status, $output ) = run_command(
        cwd => $root,
        env => \%env,
        cmd => [ '/usr/bin/prove', @tests ],
    );
    $overall = 1 if $status != 0;
    my $result = $status == 0 ? 'PASS' : 'FAIL';
    my $vendor = $include_vendor ? 'extended syntax + autoload' : 'autoload';
    push @report, "| $version | $result | " . scalar(@tests) . " files | $vendor |";
    push @details,
        "## PHP $version",
        q{},
        "Executable: `$php`",
        q{},
        'Loaded extensions: ' . join( ', ', sort @modules ),
        q{},
        '```text',
        $output,
        '```',
        q{};
}

push @report, q{}, @details;
my $report = join( "\n", @report ) . "\n";
if ( defined $report_path ) {
    open my $fh, '>', $report_path or die "write '$report_path' failed: $!\n";
    print {$fh} $report;
    close $fh or die "close '$report_path' failed: $!\n";
    print "wrote $report_path\n";
} else {
    print $report;
}
exit $overall;

sub usage {
    my ($status) = @_;
    print <<'USAGE';
Usage: tools/run_php_compatibility.pl [options]

  --php PATH          PHP executable to test; repeat for a version matrix
  --include-vendor    lint every bundled dependency PHP file
  --report PATH       write the Markdown report to PATH
  --help              show this help

GENAPP_PHP_BINARIES may contain a comma-separated executable list.
USAGE
    exit $status;
}
